version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {MyPassword}
    networks:
      - mynet

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
    networks:
      - mynet

  nginx:
    container_name: nginx
    image: nginx_test:02
    restart: always
    volumes:
      - ./code:/var/www/my-ele-project/html
    ports:
      - 80:80
      - 443:443
    networks:
      - mynet

  php-fpm:
    container_name: php-fpm
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./code:/var/www/my-ele-project/html
    networks:
      - mynet

networks:
  mynet:
